CREATE SCHEMA IF NOT EXISTS walletdb;
SET SCHEMA walletdb;
CREATE TABLE IF NOT EXISTS WALLET
    (ID VARCHAR(255) PRIMARY KEY,
    NAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    FILEPATH VARCHAR (500));